gText_Birch_Welcome::
	.string "Hi! Good to see you again!\p"
	.string "As you may already know, my name\n"
	.string "is Birch, but everyone calls me\l"
	.string "the POKéMON PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "And here is one of the many POKéMON\n"
	.string "you'll find out in the wild.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "The HOENN region has seen many new\n"
	.string "developments over the years.\p"
	.string "New POKéMON have migrated to our\n"
	.string "region, and many new trainers have\l"
	.string "followed them. And even some familiar\l"
	.string "faces have taken a liking to the new\l"
	.string "POKéMON found across HOENN.\p"
	.string "These changes have even shaped our\n"
	.string "landscape in new ways, and what you\l"
	.string "may find in our region is different\l"
	.string "than is has looked in the past.\p"
	.string "But, despite these changes, much\n"
	.string "remains the same in HOENN.\p"
	.string "In present-day HOENN, you'll see\n"
	.string "faces both new and old.\p"
	.string "Some challenges will be familiar,\n"
	.string "but many new trials await you.\p"
	.string "Before we continue, I'd like to\n"
	.string "find out a bit more about you.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
